### ISSUE TITLE
Loading issue and request

### ISSUE THREAD

**Issue by seydx** [paolotremadio/homebridge-automation-chromecast#1]
Hello,

first of all, its a great plugin. Im using it with my sony ty which has chromecast built in

Issue:
I think you have forgotten "hap-nodejs" in your package.json as dependency , without hap-nodejs the plugin will not load 

Request:
After turning off the tv, the sensor/switch says 'no response'. So is it possible to turn off the sensor/switch if there is no connection anymore instead of 'no response' ?

**Comment by paolotremadio** [comment]
Hi,

Thanks for pointing it out. I've just released v0.0.10 that addresses both the package.json and it improves the connection handling.

Try the new version and let me know if the "no response" issue is still persisting.

Cheers!

**Comment by seydx** [comment]
works great thanks!!!

**Comment by paolotremadio** [comment]
You're welcome. Feel free to suggest any improvement. I'm considering adding Volume control but I can't see any actual value into doing so.
