### ISSUE TITLE
Problem with IP-address resolving

### ISSUE THREAD

**Issue by geokvant** [paolotremadio/homebridge-automation-chromecast#16]
My homebridge says that there is a problem with this [6/26/2020, 9:58:07 PM] The plugin "homebridge-control-chromecast" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!

and every time when it starts it finds my Chromecast as 172.0.0.200 

but my home network has 192.168.1.X/24 mask

Homebridge based on Raspberry pi and homebridge.io OS image 1.0.6

Help me please to solve it - b/c your plug-in is very nice and usefull

**Comment by paolotremadio** [comment]
Hi,

About the first error, don’t worry about it. It is just a notice. It doesn’t impact the functioning of the plugin. 

Does it actually find the right chromecast? Does it work? (Does it report the correct status when you start playing)

**Comment by geokvant** [comment]
It finds it but in strange way - with wrong address **127.0.0.200** (some local address of raspbian):

`[6/27/2020, 02:23:45] [ChromecastHD] Adding a new found Chomecast: ChromecastHD [a06166a3d5e0023e487cc4ff48ad4301]
[6/27/2020, 02:23:45] [ChromecastHD] Found Chromecast: "Chromecast-a06166a3d5e0023e487cc4ff48ad4301" "ChromecastHD" at 127.0.0.200:8009
[6/27/2020, 02:23:45] [ChromecastHD] Updating chromecast info
[6/27/2020, 02:23:45] [ChromecastHD] Controlling chromecast on **127.0.0.200:8009**
[6/27/2020, 02:23:45] [ChromecastHD] Connecting to Chromecast on **127.0.0.200:8009**
[6/27/2020, 02:23:45] [ChromecastHD] Updating chromecast info`

but real IP address of my chromecast is **192.168.1.48** 

then it shows me in log this:

`[6/27/2020, 02:23:45] [ChromecastHD] Chromecast client - Error: connect ECONNREFUSED 127.0.0.200:8009
[6/27/2020, 02:23:45] [ChromecastHD] Chromecast connection: disconnected
[6/27/2020, 02:23:45] [ChromecastHD] Waiting 2 seconds before reconnecting`

and after that starts this stuff:

`[6/27/2020, 02:26:19] [ChromecastHD] Connecting to Chromecast on 127.0.0.200:8009
[6/27/2020, 02:26:19] [ChromecastHD] Chromecast client - Error: connect **ECONNREFUSED 127.0.0.200:8009**
[6/27/2020, 02:26:19] [ChromecastHD] Chromecast connection: disconnected
[6/27/2020, 02:26:19] [ChromecastHD] Waiting 2 seconds before reconnecting
[6/27/2020, 02:26:21] [ChromecastHD] Connecting to Chromecast on 127.0.0.200:8009
[6/27/2020, 02:26:21] [ChromecastHD] Chromecast client - Error: connect **ECONNREFUSED 127.0.0.200:8009**
[6/27/2020, 02:26:21] [ChromecastHD] Chromecast connection: disconnected
[6/27/2020, 02:26:21] [ChromecastHD] Waiting 2 seconds before reconnecting`


Homebridge installed on my Raspberry Pi with homebridge.io raspbian image 1.0.6. I have already tried to make a clean install, even tried  another Raspberry pi with new one homebridge - always same problem.

I have 10 other plugins and all of them work just great in my local network

is there any option to hardcode in config right IP-address of my Chromecast?

**Comment by paolotremadio** [comment]
There’s no option to hardcode the IP address, yet :) 

I'll implement that for you during the weekend

**Comment by geokvant** [comment]
> I'll implement that for you during the weekend

Thank you very much for this option:) I’m sure it will help some other users, who also uses raspberry pi for homebridge and has Chromecast👍 
I saw same error in other posts online while googled it

**Comment by geokvant** [comment]
Ups...
I've installed plugin "homebridge-automation-chromecast" 2020/06/26 version and....

`[6/27/2020, 14:53:16] Error: The requested accessory 'AutomationChromecast' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)`

and then 

`[6/27/2020, 14:53:27] ---
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[6/27/2020, 14:53:28] ====================
[6/27/2020, 14:53:28] ERROR LOADING PLUGIN homebridge-automation-chromecast:
[6/27/2020, 14:53:28] Error: Cannot find module 'hap-nodejs'
Require stack:
- /usr/local/lib/node_modules/homebridge-automation-chromecast/custom-characteristics.js
- /usr/local/lib/node_modules/homebridge-automation-chromecast/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-automation-chromecast/custom-characteristics.js:2:28)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
[6/27/2020, 14:53:28] ====================`

and after these errors in log homebridge service doesn't start at all :(

**Comment by paolotremadio** [comment]
Ok, install the latest version, I've fixed the issue that is stopping Homebridge from loading

**Comment by paolotremadio** [comment]
I've added the config for hardcoded IP/port.

Install the latest master - E.g.
`npm install -g https://github.com/paolotremadio/homebridge-automation-chromecast`

Use the following config for homebridge:
```json
{
      "accessory": "AutomationChromecast",
      "name": "Name of your choice",
      "ip": "IP",
      "port": "8009"
}
```

**Comment by geokvant** [comment]
homebridge still dies on every load :(

`[6/29/2020, 01:43:55] Error: extension not loaded yet
    at Object.serialize (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/castv2/lib/proto.js:29:15)
    at Client.send (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/castv2/lib/client.js:127:25)
    at Channel.send (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/castv2/lib/channel.js:34:12)
    at fn.Controller.send (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/castv2-client/lib/controllers/controller.js:28:16)
    at fn.ConnectionController.connect (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/castv2-client/lib/controllers/connection.js:28:8)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/castv2-client/lib/senders/platform.js:59:21)
    at Object.onceWrapper (events.js:421:28)
    at Client.emit (events.js:315:20)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/castv2/lib/client.js:40:10)
    at Object.onceWrapper (events.js:421:28)`

moreover I've installed this plugin to my test instance of homebridge on macos and have the same error and behavior
behavior of homebridge service :( service reboot all time

**Comment by paolotremadio** [comment]
What’s the IP/port of the chromecast? Also, what kind of chromecast device are you targeting?

On Mac, please download this app: https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12
Open it, look for googlecast, expand that section and all the children and send me a screenshot 😉

**Comment by geokvant** [comment]
1) I use this Chromecast second gen (2015) [this one](https://store.google.com/my/product/chromecast_2015)
https://paste.pics/9FHP3
2) IP Address:port - 192.168.1.48:8009
3) screenshot from Discovery mac app here --> https://paste.pics/9FHMC

P.S. b/t/w it shows this address 127.0.0.200 for all my devices and as I see - it caused by bonjour (mDNS) service - but all other devices (like a Daikin online local controller over Homebridge or Philips Hue bridge) work with it anyway.

just in case it can explain something: my home network based on UniFi devices ([USG](https://www.ui.com/unifi-routing/usg/), Unifi Switch, Unifi APs + Online controller installed on same Raspberry as Homebridge service)

**Comment by paolotremadio** [comment]
That’s really weird. I run my network on unifi (dream machine) and the plugin works. 

Let’s try something different. On the raspberry pi, try to run `telnet 192.168.1.48 8009`. Does it connect? Take a screenshot of the output

**Comment by paolotremadio** [comment]
Also run `traceroute 192.168.1.48`

**Comment by geokvant** [comment]
1)
`pi@hbtest:~ $ telnet 192.168.1.48 8009
Trying 192.168.1.48...
Connected to 192.168.1.48.
Escape character is '^]'.`
2)
`traceroute to 192.168.1.48 (192.168.1.48), 30 hops max, 60 byte packets
 1  Chromecast.localdomain (192.168.1.48)  3.961 ms  3.713 ms  5.558 ms`

As I can see problem is somewhere in mDNS resolving for `.local` hostnames, b/c of this: for chromecast host - resolving is OK, but for **chromecast.local** - it goes with 127.0.0.200

`pi@hbtest:~ $ ping chromecast
PING chromecast.localdomain (192.168.1.48) 56(84) bytes of data.
64 bytes from Chromecast.localdomain (192.168.1.48): icmp_seq=1 ttl=64 time=7.70 ms
64 bytes from Chromecast.localdomain (192.168.1.48): icmp_seq=2 ttl=64 time=4.59 ms
64 bytes from Chromecast.localdomain (192.168.1.48): icmp_seq=3 ttl=64 time=4.81 ms
^C
--- chromecast.localdomain ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 4ms
rtt min/avg/max/mdev = 4.587/5.700/7.699/1.416 ms
pi@hbtest:~ $ ping chromecast.local
PING chromecast.local (127.0.0.200) 56(84) bytes of data.
64 bytes from 127.0.0.200 (127.0.0.200): icmp_seq=1 ttl=64 time=0.110 ms
64 bytes from 127.0.0.200 (127.0.0.200): icmp_seq=2 ttl=64 time=0.131 ms
^C
--- chromecast.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 3ms
rtt min/avg/max/mdev = 0.110/0.120/0.131/0.015 ms`

but, anyway - can't understand - why it goes this way even if I put IP Address 192.168.1.48 to config

**Comment by paolotremadio** [comment]
It’s really strange. Let me run some tests and I’ll get back to you. Meanwhile, try to disable mdns repeater via the unifi UI. Does it resolve the correct ip when pinging the `.local` domain for chromecast? (Also allow a few seconds for the usg ti provision before running the test)

**Comment by geokvant** [comment]
in USG over UniFi controller I can only disable mDNS Service - now it's disabled

`This option enables the mDNS reflector service on the UniFi Security Gateway 3P. This repeats mDNS traffic out all interfaces of the UniFi Security Gateway 3P other than the one it was received on, so it will work across separate interfaces and VLANs, including between guest and corporate VLANs.` - now it's disabled

when I try to ping Chromecast - it  returns 192.168.1.48 with packets for full network name Chromecast.localdomain
when I try to ping Chromecast.local - it returns 127.0.0.200 and no response

but for NSLookUp
```
pi@rpi3:/var/lib/homebridge $ nslookup chromecast
Server:         192.168.1.1
Address:        192.168.1.1#53

Name:   chromecast.localdomain
Address: 192.168.1.48

pi@rpi3:/var/lib/homebridge $ nslookup chromecast.local
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
Name:   chromecast.local
Address: 127.0.0.200

```
same for any other device

but during these few hours I've spent with my network I had some period when plugin worked for me, but in that moment iphone's youtube client couldn't send video to Chromecast...

**Comment by paolotremadio** [comment]
I did a further test: configuring by IP might not be wise. The current bonjour based setup is fault tolerant: if you reboot your chromecast, it will detect it and reconnect. Setting up by IP will not handle it. Further more, the chromecast must be already online by the time homebridge starts or it will fail. I will revert the changes. Please do investigate what's up with your network. It is really weird, I run multiple VLANs on Unifi and I've never seen the issue you're reporting.

Double check your network masks, VLAN configurations. Chromecast is somehow announcing 2 IP addresses, one on the 127.x.x.x block (you get two IP addresses on the mac as well as from the plugin on RPI). You should fix that issue to make it work.

Have you tried to search online for this issue?

**Comment by paolotremadio** [comment]
I close it for now, feel free to re-open as soon as you have more info 😉

**Comment by geokvant** [comment]
Thanks for your try to add IP address. While I tried to solve it I've broke my local network two times, readopted 2 of 5 unifi devices and almost lost my unifi controller but only Chromecast doesn't want to work it this configuration and resolves 127.0.0.200 - all other devices also have this secondary IP-address (with different ports) but work with mDNS somehow (I have about 20+ different devices).
I think to make another test network with mikrotik and only 2 devices in it to find out - who is the creator of this 127.0.0.200 address generator.

**Comment by geokvant** [comment]
Hi.

I've made some tests and now it obvious that this Address 127.0.0.200 generated by homebridge instance installed on my Raspberry pi (with Raspberry OS - this one distro https://github.com/homebridge/homebridge-raspbian-image/releases/tag/v1.0.7 )
As I said before - all other devices (i have 
1) homebridged sonos, Shelly, Daikin, Roborock, taHoma, Samsung Tizen - all work good and stable
 and 
2) native homekit gadgets like Aqara, Hue, Eve

but only this Chromecast plug-in resolves only 127.0.0.200 IP-address and can't connect to homekit

Also I've tried to install homebridge to my MacBook and totally disconnect homebridge on Raspberry pi - in this case chromecast can be managed, so i do believe that problem is somewhere in mdns of plugin and mdns of official [homebridge distro of Raspbian OS](https://github.com/homebridge/homebridge-raspbian-image/releases/tag/v1.0.7).

do you have an option to test this chromecast plugin with homebridge.io and raspberry pi?

**Comment by paolotremadio** [comment]
Can you run ‘ifconfig’ on your RPI and send the the output?

**Comment by geokvant** [comment]
sure
`
pi@homebridge:/var/lib/homebridge $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.234  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::dea6:32ff:fe7f:2e50  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:7f:2e:50  txqueuelen 1000  (Ethernet)
        RX packets 6026651  bytes 2323452182 (2.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3118496  bytes 791504526 (754.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 5528761  bytes 1999290358 (1.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5528761  bytes 1999290358 (1.8 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether fa:97:29:21:cc:ef  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

**Comment by paolotremadio** [comment]
This is weird... @oznu any idea of why this would happen? I've never used the homebridge RPI images so I'm not an expert about it :|
