### ISSUE TITLE
No slider for volume & disable motion sensor

### ISSUE THREAD

**Issue by joerexlo** [paolotremadio/homebridge-automation-chromecast#20]
Hi - is there a way to enable slider for volume control. Also please give an option to disable motion sensor.

**Comment by paolotremadio** [comment]
Hi, there's a volume control but it is not visibile on the iOS Home app. This plugin was created before there was the support for volume. It could be enabled.

What do you mean with "disable the motion sensor"?

**Comment by joerexlo** [comment]
Ok so how do i enable then for volume control.
Motion sensor - Since i am not using it and using only switch wanted that to not show up. the other reason mainly is since homekit groups them together i have click on the switch and then click off. It makes it 2 clicks. I think by removing the ungrouping will solve this or removing the motion sensor will solve this. hope its clear.

**Comment by paolotremadio** [comment]
I don’t think I’ll we have the bandwidth to make those changes. But a PR is always welcome
