### ISSUE TITLE
Installing fails

### ISSUE THREAD

**Issue by brampk136** [paolotremadio/homebridge-automation-chromecast#22]
Tried installing this plugin om my Pi Zero. Getting this.
<img width="653" alt="Schermafbeelding 2022-02-04 om 20 46 58" src="https://user-images.githubusercontent.com/95961420/152593897-c4f7e302-dfc1-4f81-a6d0-51f1a96260b2.png">

**Comment by paolotremadio** [comment]
What version of node are you running?

**Comment by brampk136** [comment]
Node.js v16.13.2
Npm v8.3.1

**Comment by paolotremadio** [comment]
Have you tried a lower version of node? Like v12/v14. V16 is fairly recent, there might be an issue with a dependency

**Comment by brampk136** [comment]
Tried a random version of v14 (v14.18.1). Now the plugin does install. But after setting it up and restarting HB this message appears in the log: 
_No plugin was found for the accessory "AutomationChromecast" in your config.json. Please make sure the corresponding plugin is installed correctly._
