### ISSUE TITLE
unable to load the plugin

### ISSUE THREAD

**Issue by Hussamfhaily** [paolotremadio/homebridge-automation-chromecast#5]
I get this error: /usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build/Release/dns_sd_bindings.node: invalid ELF header

homebridge doesn't run because of that error.

**Comment by paolotremadio** [comment]
Which platform are you running on?

**Comment by Hussamfhaily** [comment]
Raspberry Pi 3 B+.

**Comment by paolotremadio** [comment]
Node version? I also need to know the distro you’re running on the raspberry pi. 

It’s not loading one of the libraries. So I have to find out how to reproduce it first :)

**Comment by Hussamfhaily** [comment]
Node v8.11.1. Thanks for your effort.

**Comment by Hussamfhaily** [comment]
module mdns could not be installed

**Comment by paolotremadio** [comment]
Have  you tried installing mdns module globally? I'm running on the same hardware and node version and it works. Please help me out troubleshooting as I cannot reproduce on my hardware :|
